export const VACUUM_STATE_CLEANING = 'cleaning';
export const VACUUM_STATE_DOCKED = 'docked';
export const VACUUM_STATE_ERROR = 'error';
export const VACUUM_STATE_IDLE = 'idle';
export const VACUUM_STATE_PAUSE = 'paused';
export const VACUUM_STATE_RETURNING = 'returning';
export const VACUUM_STATE_UNAVAILABLE = 'unavailable';
export const VACUUM_STATE_UNKNOWN = 'unknown';

export const VACUUM_FAN_SPEED_SILENT = 'Silent';
export const VACUUM_FAN_SPEED_STANDARD = 'Standard';
export const VACUUM_FAN_SPEED_MEDIUM = 'Medium';
export const VACUUM_FAN_SPEED_TURBO = 'Turbo';

export const VACUUM_FAN_SPEED_MODE = [
  VACUUM_FAN_SPEED_SILENT,
  VACUUM_FAN_SPEED_STANDARD,
  VACUUM_FAN_SPEED_MEDIUM,
  VACUUM_FAN_SPEED_TURBO,
];

export const VACUUM_ICONS = {};
VACUUM_ICONS[VACUUM_STATE_CLEANING] = 'mdi:robot-vacuum';
VACUUM_ICONS[VACUUM_STATE_DOCKED] = 'sci:vacuum-docked';
VACUUM_ICONS[VACUUM_STATE_ERROR] = 'mdi:robot-vacuum-alert';
VACUUM_ICONS[VACUUM_STATE_IDLE] = 'sci:vacuum-sleep';
VACUUM_ICONS[VACUUM_STATE_PAUSE] = 'sci:vacuum-sleep';
VACUUM_ICONS[VACUUM_STATE_RETURNING] = 'mdi:robot-vacuum';
VACUUM_ICONS[VACUUM_STATE_UNAVAILABLE] = 'mdi:robot-vacuum-off';
VACUUM_ICONS[VACUUM_STATE_UNKNOWN] = 'mdi:robot-vacuum-off';

export const VACUUM_ACTIVITY_CLEAN = 'CLEAN';
export const VACUUM_ACTIVITY_RETURNING = 'RETURNING';
export const VACUUM_ACTIVITY_IDLE = 'IDLE';
export const VACUUM_ACTIVITY_DOCKED = 'DOCKED';
export const VACUUM_ACTIVITY_ALERT = 'ALERT';
export const VACUUM_ACTIVITY_STATE = {};
VACUUM_ACTIVITY_STATE[VACUUM_STATE_CLEANING] = VACUUM_ACTIVITY_CLEAN;
VACUUM_ACTIVITY_STATE[VACUUM_STATE_DOCKED] = VACUUM_ACTIVITY_DOCKED;
VACUUM_ACTIVITY_STATE[VACUUM_STATE_ERROR] = VACUUM_ACTIVITY_ALERT;
VACUUM_ACTIVITY_STATE[VACUUM_STATE_IDLE] = VACUUM_ACTIVITY_IDLE;
VACUUM_ACTIVITY_STATE[VACUUM_STATE_PAUSE] = VACUUM_ACTIVITY_IDLE;
VACUUM_ACTIVITY_STATE[VACUUM_STATE_RETURNING] = VACUUM_ACTIVITY_RETURNING;
VACUUM_ACTIVITY_STATE[VACUUM_STATE_UNAVAILABLE] = VACUUM_ACTIVITY_ALERT;
VACUUM_ACTIVITY_STATE[VACUUM_STATE_UNKNOWN] = VACUUM_ACTIVITY_ALERT;

export const VACUUM_ACTION_START = 'start';
export const VACUUM_ACTION_PAUSE = 'pause';
export const VACUUM_ACTION_STOP = 'stop';
export const VACUUM_ACTION_RETURN_TO_BASE = 'return_to_base';
export const VACUUM_ACTIONS_ICONS = {};
VACUUM_ACTIONS_ICONS[VACUUM_ACTION_START] = 'mdi:play-circle-outline';
VACUUM_ACTIONS_ICONS[VACUUM_ACTION_PAUSE] = 'mdi:pause-circle-outline';
VACUUM_ACTIONS_ICONS[VACUUM_ACTION_STOP] = 'mdi:stop-circle-outline';
VACUUM_ACTIONS_ICONS[VACUUM_ACTION_RETURN_TO_BASE] = 'mdi:home-import-outline';
