export const WEATHER_STATE_FR = {
  clear: 'Ciel dégagé',
  'clear-night': 'Nuit claire',
  cloudy: 'Nuageux',
  exceptional: 'Exceptionnel',
  fog: 'Brouillard',
  hail: 'Risque de grèle',
  lightning: 'Orages',
  'lightning-rainy': 'Pluie orageuse',
  partlycloudy: 'Eclaircies',
  pouring: 'Pluie forte',
  rainy: 'Pluie',
  snowy: 'Neige',
  'snowy-rainy': 'Pluie verglaçante',
  sunny: 'Ensoleillé',
  windy: 'Venteux',
  'windy-variant': 'Venteux variable',
};
