// ─── Mock HASS states ────────────────────────────────────────────────────
// Données extraites des yaml backup/*.yaml — fidèles à la production
export const MOCK_STATES = {
  'weather.la_chapelle_sur_erdre': {
    entity_id: 'weather.la_chapelle_sur_erdre', state: 'partlycloudy', attributes: {
      friendly_name: 'La Chapelle-sur-Erdre', temperature: 19.5, humidity: 68, wind_speed: 14, forecast: [
        { datetime: new Date(Date.now()).toISOString(), condition: 'partlycloudy', temperature: 22, templow: 14 },
        { datetime: new Date(Date.now() + 86400000).toISOString(), condition: 'rainy', temperature: 18, templow: 12 },
        { datetime: new Date(Date.now() + 172800000).toISOString(), condition: 'sunny', temperature: 25, templow: 15 },
        { datetime: new Date(Date.now() + 259200000).toISOString(), condition: 'cloudy', temperature: 20, templow: 13 },
        { datetime: new Date(Date.now() + 345600000).toISOString(), condition: 'sunny', temperature: 27, templow: 16 },
      ]
    }
  },
  'sensor.44_weather_alert': { entity_id: 'sensor.44_weather_alert', state: 'Vert', attributes: { friendly_name: 'Alerte météo 44' } },
  'climate.clou': { entity_id: 'climate.clou', state: 'heat', attributes: { friendly_name: 'Clou', hvac_mode: 'heat', hvac_modes: ['off', 'heat', 'cool'], current_temperature: 21.5, temperature: 22, preset_mode: 'eco', preset_modes: ['none', 'eco'], min_temp: 15, max_temp: 30 } },
  'sensor.clou_combustion_chamber_temperature': { entity_id: 'sensor.clou_combustion_chamber_temperature', state: '340', attributes: { unit_of_measurement: '°C' } },
  'sensor.frient_smoke_detector_salon_temperature': { entity_id: 'sensor.frient_smoke_detector_salon_temperature', state: '21.5', attributes: { unit_of_measurement: '°C', friendly_name: 'Temp. salon' } },
  'sensor.clou_fan_speed': { entity_id: 'sensor.clou_fan_speed', state: '3', attributes: { unit_of_measurement: '' } },
  'sensor.clou_pressure': { entity_id: 'sensor.clou_pressure', state: '1.2', attributes: { unit_of_measurement: 'mbar' } },
  'sensor.clou_power': { entity_id: 'sensor.clou_power', state: '7.5', attributes: { unit_of_measurement: 'kW' } },
  'sensor.smart_energy_monitor_poele_power': { entity_id: 'sensor.smart_energy_monitor_poele_power', state: '65', attributes: { unit_of_measurement: 'W' } },
  'sensor.clou_pellet_quantity': { entity_id: 'sensor.clou_pellet_quantity', state: '45', attributes: { unit_of_measurement: '%' } },
  'sensor.clou_time_to_service': { entity_id: 'sensor.clou_time_to_service', state: '234', attributes: { unit_of_measurement: 'h' } },
  'binary_sensor.clou_stove_status': { entity_id: 'binary_sensor.clou_stove_status', state: 'on', attributes: { friendly_name: 'Statut poêle' } },
  'counter.pellet_stock': { entity_id: 'counter.pellet_stock', state: '8', attributes: { friendly_name: 'Stock sacs', minimum: 0, maximum: 20 } },
  'vacuum.dobby': { entity_id: 'vacuum.dobby', state: 'docked', attributes: { friendly_name: 'Dobby', fan_speed: 'Standard', fan_speed_list: ['Silent', 'Standard', 'Boost', 'MAX'] } },
  'sensor.s7_batterie': { entity_id: 'sensor.s7_batterie', state: '100', attributes: { unit_of_measurement: '%', icon: 'mdi:battery' } },
  'select.s7_intensite_de_frottement': { entity_id: 'select.s7_intensite_de_frottement', state: 'Intense', attributes: { friendly_name: 'Intensité frottement', options: ['Standard', 'Fort', 'Maximum', 'Doux', 'Intense'] } },
  'sensor.s7_surface_de_nettoyage': { entity_id: 'sensor.s7_surface_de_nettoyage', state: '47', attributes: { unit_of_measurement: 'm²' } },
  'sensor.s7_duree_de_nettoyage': { entity_id: 'sensor.s7_duree_de_nettoyage', state: '38', attributes: { unit_of_measurement: 'min' } },
  'image.s7_map_0': { entity_id: 'image.s7_map_0', state: 'idle', attributes: {} },
  'binary_sensor.captur_ii_en_charge': { entity_id: 'binary_sensor.captur_ii_en_charge', state: 'off', attributes: { friendly_name: 'Captur II en charge' } },
  'binary_sensor.captur_ii_serrure': { entity_id: 'binary_sensor.captur_ii_serrure', state: 'locked', attributes: { friendly_name: 'Serrure' } },
  'binary_sensor.eau_active': { entity_id: 'binary_sensor.eau_active', state: 'off', attributes: { friendly_name: 'Eau Active' } },
  'device_tracker.captur_ii_emplacement': { entity_id: 'device_tracker.captur_ii_emplacement', state: 'home', attributes: {} },
  'sensor.captur_ii_autonomie_de_la_batterie': { entity_id: 'sensor.captur_ii_autonomie_de_la_batterie', state: '42', attributes: { unit_of_measurement: 'km' } },
  'sensor.captur_ii_autonomie_en_carburant': { entity_id: 'sensor.captur_ii_autonomie_en_carburant', state: '380', attributes: { unit_of_measurement: 'km' } },
  'sensor.captur_ii_batterie': { entity_id: 'sensor.captur_ii_batterie', state: '72', attributes: { unit_of_measurement: '%' } },
  'sensor.captur_ii_etat_du_branchement': { entity_id: 'sensor.captur_ii_etat_du_branchement', state: 'unplugged', attributes: {} },
  'sensor.captur_ii_kilometrage': { entity_id: 'sensor.captur_ii_kilometrage', state: '28540', attributes: { unit_of_measurement: 'km' } },
  'sensor.captur_ii_quantite_de_carburant': { entity_id: 'sensor.captur_ii_quantite_de_carburant', state: '38', attributes: { unit_of_measurement: 'L' } },
  'sensor.captur_ii_temps_de_charge_restant': { entity_id: 'sensor.captur_ii_temps_de_charge_restant', state: '0', attributes: { unit_of_measurement: 'min' } },
  'switch.nous_ventilateur_leonard': { entity_id: 'switch.nous_ventilateur_leonard', state: 'on', attributes: { friendly_name: 'Ventilateur Léonard' } },
  'number.nous_ventilateur_leonard_countdown': { entity_id: 'number.nous_ventilateur_leonard_countdown', state: '0', attributes: { unit_of_measurement: 'min' } },
  'select.nous_ventilateur_leonard_power_outage_memory': { entity_id: 'select.nous_ventilateur_leonard_power_outage_memory', state: 'Power On', attributes: { friendly_name: 'Power outage memory', options: ['Power On', 'Power Off', 'Last State'] } },
  'sensor.nous_ventilateur_leonard_power': { entity_id: 'sensor.nous_ventilateur_leonard_power', state: '18', attributes: { unit_of_measurement: 'W' } },
  'switch.nous_ventilateur_leonard_child_lock': { entity_id: 'switch.nous_ventilateur_leonard_child_lock', state: 'off', attributes: {} },
  'sensor.nous_ventilateur_leonard_energy': { entity_id: 'sensor.nous_ventilateur_leonard_energy', state: '4.87', attributes: { unit_of_measurement: 'kWh' } },
  'switch.mureva_evlink': { entity_id: 'switch.mureva_evlink', state: 'off', attributes: { friendly_name: 'EvLink' } },
  'sensor.mureva_evlink_energy_corrected': { entity_id: 'sensor.mureva_evlink_energy_corrected', state: '142.5', attributes: { unit_of_measurement: 'kWh' } },
  'binary_sensor.mureva_evlink_charge': { entity_id: 'binary_sensor.mureva_evlink_charge', state: 'off', attributes: {} },
  'sensor.mureva_evlink_current': { entity_id: 'sensor.mureva_evlink_current', state: '0', attributes: { unit_of_measurement: 'A' } },
  'select.mureva_evlink_power_on_behavior': { entity_id: 'select.mureva_evlink_power_on_behavior', state: 'Power On', attributes: { friendly_name: 'Power-on behavior', options: ['Power On', 'Power Off', 'Last State'] } },
  'sensor.mureva_evlink_power_corrected': { entity_id: 'sensor.mureva_evlink_power_corrected', state: '0', attributes: { unit_of_measurement: 'W' } },
  'switch.nous_paillette_charlotte': { entity_id: 'switch.nous_paillette_charlotte', state: 'on', attributes: {} },
  'sensor.nous_paillette_charlotte_energy': { entity_id: 'sensor.nous_paillette_charlotte_energy', state: '0.45', attributes: { unit_of_measurement: 'kWh' } },
  'sensor.nous_paillette_charlotte_power': { entity_id: 'sensor.nous_paillette_charlotte_power', state: '11.2', attributes: { unit_of_measurement: 'W' } },
  'switch.nous_paillette_charlotte_child_lock': { entity_id: 'switch.nous_paillette_charlotte_child_lock', state: 'off', attributes: {} },
  'select.nous_paillette_charlotte_power_outage_memory': { entity_id: 'select.nous_paillette_charlotte_power_outage_memory', state: 'Power On', attributes: { friendly_name: 'Power outage memory', options: ['Power On', 'Power Off', 'Last State'] } },
  'climate.radiateur_salon': { entity_id: 'climate.radiateur_salon', state: 'heat', attributes: { friendly_name: 'Salon', hvac_mode: 'heat', hvac_modes: ['off', 'heat', 'cool'], current_temperature: 20.5, temperature: 21, preset_mode: 'comfort', preset_modes: ['none', 'eco'] } },
  'climate.radiateur_salon_2': { entity_id: 'climate.radiateur_salon_2', state: 'off', attributes: { friendly_name: 'Salon 2', hvac_mode: 'off', hvac_modes: ['off', 'heat', 'cool'], current_temperature: 20, temperature: null, preset_mode: 'none', preset_modes: ['none', 'eco'] } },
  'climate.radiateur_cuisine': { entity_id: 'climate.radiateur_cuisine', state: 'auto', attributes: { friendly_name: 'Cuisine', hvac_mode: 'auto', hvac_modes: ['off', 'heat', 'cool'], current_temperature: 19, temperature: 20, preset_mode: 'eco', preset_modes: ['none', 'eco'] } },
  'climate.radiateur_chambre': { entity_id: 'climate.radiateur_chambre', state: 'off', attributes: { friendly_name: 'Chambre parents', hvac_mode: 'off', hvac_modes: ['off', 'heat', 'cool'], current_temperature: 17, temperature: null, preset_mode: 'frost_protection', preset_modes: ['none', 'eco', 'frost_protection'] } },
  'climate.radiateur_bureau': { entity_id: 'climate.radiateur_bureau', state: 'heat', attributes: { friendly_name: 'Bureau', hvac_mode: 'heat', hvac_modes: ['off', 'heat', 'cool'], current_temperature: 21, temperature: 22, preset_mode: 'comfort-1', preset_modes: ['none', 'eco', 'comfort-1'] } },
  'light.zbmini_l_salon': { entity_id: 'light.zbmini_l_salon', state: 'on', attributes: { friendly_name: 'Plafond salon' } },
  'light.zbmini_l_cuisine': { entity_id: 'light.zbmini_l_cuisine', state: 'off', attributes: {} },
  'light.zbmini_l_bureau': { entity_id: 'light.zbmini_l_bureau', state: 'on', attributes: {} },
  'light.zbmini_l_parent': { entity_id: 'light.zbmini_l_parent', state: 'off', attributes: {} },
  'light.zbmini_l_charlotte': { entity_id: 'light.zbmini_l_charlotte', state: 'off', attributes: {} },
  'light.zbmini_l_leonard': { entity_id: 'light.zbmini_l_leonard', state: 'on', attributes: {} },
  'light.zbmini_l_mezzanine': { entity_id: 'light.zbmini_l_mezzanine', state: 'off', attributes: {} },
  'light.nous_salon': { entity_id: 'light.nous_salon', state: 'on', attributes: { friendly_name: 'Étoile salon' } },
  'light.zbmini_l_lampe_salon': { entity_id: 'light.zbmini_l_lampe_salon', state: 'off', attributes: {} },
  'media_player.bravia_4k_vh22': { entity_id: 'media_player.bravia_4k_vh22', state: 'off', attributes: { volume_level: 0.0, friendly_name: 'Bravia 4K TV' } },
  'remote.bravia_4k_vh22': { entity_id: 'remote.bravia_4k_vh22', state: 'off', attributes: { friendly_name: 'Bravia Remote' } },
  'switch.plugs': { entity_id: 'switch.plugs', state: 'on', attributes: {} },
  'person.adrien': { entity_id: 'person.adrien', state: 'home', attributes: { friendly_name: 'Adrien' } },
  'person.virginie': { entity_id: 'person.virginie', state: 'home', attributes: { friendly_name: 'Virginie' } },
  'person.root': { entity_id: 'person.root', state: 'home', attributes: { friendly_name: 'root' } },
  'person.mttq_adm': { entity_id: 'person.mttq_adm', state: 'not_home', attributes: { friendly_name: 'mttq_adm' } },
  'switch.arrosage_terrasse': { entity_id: 'switch.arrosage_terrasse', state: 'off', attributes: { friendly_name: 'Arrosage Terrasse', icon: 'mdi:sprinkler' } },
  'switch.arrosage_haie': { entity_id: 'switch.arrosage_haie', state: 'off', attributes: { friendly_name: 'Arrosage Haie', icon: 'mdi:sprinkler' } },
  'sensor.arrosage_batterie': { entity_id: 'sensor.arrosage_batterie', state: '75', attributes: { unit_of_measurement: '%', friendly_name: 'Batterie Arrosage', icon: 'mdi:battery-70' } },
  'water_heater.chauffe_eau': { entity_id: 'water_heater.chauffe_eau', state: 'eco', attributes: { friendly_name: 'Chauffe Eau', icon: 'mdi:water-boiler' } },
  'select.nodon_chauffe_eau_switch_type_on_off_2': { entity_id: 'select.nodon_chauffe_eau_switch_type_on_off_2', state: 'previous', attributes: { friendly_name: 'Switch Type', options: ['off', 'on', 'toggle', 'previous'] } },
  'sensor.nodon_chauffe_eau_linkquality': { entity_id: 'sensor.nodon_chauffe_eau_linkquality', state: '255', attributes: { friendly_name: 'Linkquality', unit_of_measurement: 'lqi' } },
  'sensor.nodon_chauffe_eau_power': { entity_id: 'sensor.nodon_chauffe_eau_power', state: '2500', attributes: { friendly_name: 'Power', unit_of_measurement: 'W' } },
  'switch.giex_valve_water': { entity_id: 'switch.giex_valve_water', state: 'off', attributes: { friendly_name: 'Water Valve' } },
  'sensor.giex_valve_battery': { entity_id: 'sensor.giex_valve_battery', state: '80', attributes: { friendly_name: 'Battery', unit_of_measurement: '%' } },
};

export const MOCK_AREAS = {
  'salon': { area_id: 'salon', name: 'Salon', floor_id: 'rdc', icon: 'mdi:sofa-outline' },
  'cuisine': { area_id: 'cuisine', name: 'Cuisine', floor_id: 'rdc', icon: 'mdi:silverware-fork-knife' },
  'bureau': { area_id: 'bureau', name: 'Bureau', floor_id: 'rdc', icon: 'mdi:desk-lamp' },
  'chambre': { area_id: 'chambre', name: 'Chambre parents', floor_id: 'r1', icon: 'mdi:bed-king-outline' },
  'charlotte': { area_id: 'charlotte', name: 'Charlotte', floor_id: 'r1', icon: 'mdi:lava-lamp' },
  'leonard': { area_id: 'leonard', name: 'Léonard', floor_id: 'r1', icon: 'mdi:robot-toy' },
  'mezzanine': { area_id: 'mezzanine', name: 'Mezzanine', floor_id: 'r1', icon: 'mdi:stairs' },
  'terrasse': { area_id: 'terrasse', name: 'Terrasse', floor_id: 'ext', icon: 'mdi:patio' },
  'jardin': { area_id: 'jardin', name: 'Jardin', floor_id: 'ext', icon: 'mdi:pine-tree' },
  'garage': { area_id: 'garage', name: 'Garage', floor_id: 'rdc', icon: 'mdi:garage' },
};

export const MOCK_FLOORS = {
  'rdc': { floor_id: 'rdc', name: 'RDC', level: 0 },
  'r1': { floor_id: 'r1', name: 'R+1', level: 1 },
  'ext': { floor_id: 'ext', name: 'Extérieur', level: 0 },
};

export const MOCK_ENTITIES = {
  'light.zbmini_l_salon': { entity_id: 'light.zbmini_l_salon', area_id: 'salon' },
  'light.nous_salon': { entity_id: 'light.nous_salon', area_id: 'salon' },
  'light.zbmini_l_lampe_salon': { entity_id: 'light.zbmini_l_lampe_salon', area_id: 'salon' },
  'light.zbmini_l_cuisine': { entity_id: 'light.zbmini_l_cuisine', area_id: 'cuisine' },
  'light.zbmini_l_bureau': { entity_id: 'light.zbmini_l_bureau', area_id: 'bureau' },
  'light.zbmini_l_parent': { entity_id: 'light.zbmini_l_parent', area_id: 'chambre' },
  'light.zbmini_l_charlotte': { entity_id: 'light.zbmini_l_charlotte', area_id: 'charlotte' },
  'light.zbmini_l_leonard': { entity_id: 'light.zbmini_l_leonard', area_id: 'leonard' },
  'light.zbmini_l_mezzanine': { entity_id: 'light.zbmini_l_mezzanine', area_id: 'mezzanine' },
  'climate.clou': { entity_id: 'climate.clou', area_id: 'salon' },
  'climate.radiateur_salon': { entity_id: 'climate.radiateur_salon', area_id: 'salon' },
  'climate.radiateur_salon_2': { entity_id: 'climate.radiateur_salon_2', area_id: 'salon' },
  'climate.radiateur_cuisine': { entity_id: 'climate.radiateur_cuisine', area_id: 'cuisine' },
  'climate.radiateur_chambre': { entity_id: 'climate.radiateur_chambre', area_id: 'chambre' },
  'climate.radiateur_bureau': { entity_id: 'climate.radiateur_bureau', area_id: 'bureau' },
  'switch.arrosage_terrasse': { entity_id: 'switch.arrosage_terrasse', area_id: 'terrasse', labels: ['water'] },
  'switch.arrosage_haie': { entity_id: 'switch.arrosage_haie', area_id: 'jardin', labels: ['water'] },
  'sensor.arrosage_batterie': { entity_id: 'sensor.arrosage_batterie', area_id: 'terrasse', labels: ['water'] },
  'water_heater.chauffe_eau': { entity_id: 'water_heater.chauffe_eau', area_id: 'garage', labels: ['water'] },
  'select.nodon_chauffe_eau_switch_type_on_off_2': { entity_id: 'select.nodon_chauffe_eau_switch_type_on_off_2', area_id: 'garage', labels: ['water'], device_id: 'nodon_chauffe_eau_device' },
  'sensor.nodon_chauffe_eau_linkquality': { entity_id: 'sensor.nodon_chauffe_eau_linkquality', area_id: 'garage', labels: ['water'], device_id: 'nodon_chauffe_eau_device' },
  'sensor.nodon_chauffe_eau_power': { entity_id: 'sensor.nodon_chauffe_eau_power', area_id: 'garage', labels: ['water'], device_id: 'nodon_chauffe_eau_device' },
  'switch.giex_valve_water': { entity_id: 'switch.giex_valve_water', area_id: 'terrasse', labels: ['water'], device_id: 'giex_valve_device' },
  'sensor.giex_valve_battery': { entity_id: 'sensor.giex_valve_battery', area_id: 'terrasse', labels: ['water'], device_id: 'giex_valve_device' },
};

export const MOCK_DEVICES = {
  '31428114e049a5557c8a8a05e2b7f9bd': { id: '31428114e049a5557c8a8a05e2b7f9bd', name: 'Ventilateur Léonard', manufacturer: 'Nous', model: 'A1T', area_id: 'leonard' },
  'a041422639f495ca70ed05e3a74ff183': { id: 'a041422639f495ca70ed05e3a74ff183', name: 'EvLink', manufacturer: 'Schneider Electric', model: 'Mureva', area_id: 'salon' },
  '7ae536ffff7d2371aadcdbc90750108d': { id: '7ae536ffff7d2371aadcdbc90750108d', name: 'Paillette Charlotte', manufacturer: 'Nous', model: 'A1T', area_id: 'charlotte' },
  'nodon_chauffe_eau_device': { id: 'nodon_chauffe_eau_device', name: 'NodOn Chauffe Eau', manufacturer: 'NodOn', model: 'SIN-4-1-20', area_id: 'garage' },
  'giex_valve_device': { id: 'giex_valve_device', name: 'Giex Valve', manufacturer: 'GiEX', model: 'GX02', area_id: 'terrasse' },
};
