export default {
  vehicles: [
    {
      name: 'Car N°1',
      mileage: 'sensor.captur_ii_kilometrage',
      location: 'device_tracker.captur_ii_emplacement',
      location_last_activity:
        'sensor.captur_ii_derniere_activite_de_localisation',
      rear_left_door_status: 'binary_sensor.captur_ii_porte_arriere_gauche',
      rear_right_door_status: 'binary_sensor.captur_ii_porte_arriere_droite',
      driver_door_status: 'binary_sensor.captur_ii_porte_conducteur',
      passenger_door_status: 'binary_sensor.captur_ii_porte_passager',
      lock_status: 'binary_sensor.captur_ii_serrure',
      charging: 'binary_sensor.captur_ii_en_charge',
      plugged_in: 'binary_sensor.captur_ii_prise',
      hatch_status: 'binary_sensor.captur_ii_trappe',
      battery_autonomy: 'sensor.captur_ii_autonomie_de_la_batterie',
      battery_level: 'sensor.captur_ii_batterie',
      battery_last_activity:
        'sensor.captur_ii_derniere_activite_de_la_batterie',
      charge_state: 'sensor.captur_ii_etat_de_charge',
      plug_state: 'sensor.captur_ii_etat_du_branchement',
      charging_remaining_time: 'sensor.captur_ii_temps_de_charge_restant',
      fuel_autonomy: 'sensor.captur_ii_autonomie_en_carburant',
      fuel_quantity: 'sensor.captur_ii_quantite_de_carburant',
    },
    {
      name: 'Car N°2',
      charging: 'binary_sensor.captur_ii_en_charge',
      rear_left_door_status: 'binary_sensor.captur_ii_porte_arriere_gauche',
      driver_door_status: 'binary_sensor.captur_ii_porte_conducteur',
      passenger_door_status: 'binary_sensor.captur_ii_porte_passager',
      plugged_in: 'binary_sensor.captur_ii_prise',
      lock_status: 'binary_sensor.captur_ii_serrure',
      hatch_status: 'binary_sensor.captur_ii_trappe',
      location: 'device_tracker.captur_ii_emplacement',
      battery_autonomy: 'sensor.captur_ii_autonomie_de_la_batterie',
      fuel_autonomy: 'sensor.captur_ii_autonomie_en_carburant',
      battery_level: 'sensor.captur_ii_batterie',
      battery_last_activity:
        'sensor.captur_ii_derniere_activite_de_la_batterie',
      location_last_activity:
        'sensor.captur_ii_derniere_activite_de_localisation',
      charge_state: 'sensor.captur_ii_etat_de_charge',
      plug_state: 'sensor.captur_ii_etat_du_branchement',
      mileage: 'sensor.captur_ii_kilometrage',
      fuel_quantity: 'sensor.captur_ii_quantite_de_carburant',
      charging_remaining_time: 'sensor.captur_ii_temps_de_charge_restant',
    },
  ],
};
