export default {
  header_message: 'Welcome back!',
  weather: {
    activate: true,
    weather_entity: 'weather.la_chapelle_sur_erdre',
    link: '?component=weather',
    weather_alert_entity: 'sensor.44_weather_alert',
    state_green: 'Vert',
    state_yellow: 'Jaune',
    state_orange: 'Orange',
    state_red: 'Rouge',
  },
  tiles: [
    {
      standalone: false,
      entity_kind: 'light',
      entities_to_exclude: ['light.ampoule_moes_toilette_bas'],
      active_icon: 'mdi:lightbulb-on-outline',
      inactive_icon: 'mdi:lightbulb-outline',
      name: 'Ligths',
      state_on: ['on'],
      state_error: null,
      link: '?component=lights',
      visibility: ['person.adrien'],
    },
    {
      standalone: true,
      entity: 'binary_sensor.captur_ii_en_charge',
      active_icon: 'sci:landspeeder',
      inactive_icon: 'sci:landspeeder',
      name: 'Cars',
      state_on: ['on'],
      state_error: null,
      link: '?component=vehicles',
      visibility: ['person.adrien'],
    },
    {
      standalone: true,
      entity: 'climate.clou',
      active_icon: 'sci:stove-heat',
      inactive_icon: 'sci:stove-off',
      name: 'Stove',
      state_on: ['heat', 'cool'],
      state_error: null,
      link: '?component=stove',
      visibility: ['person.adrien'],
    },
    {
      standalone: true,
      entity: 'vacuum.error',
      active_icon: 'mdi:robot-vacuum',
      inactive_icon: 'sci:vacuum-sleep',
      name: 'Dobby',
      state_on: ['cleaning', 'returning'],
      state_error: 'error',
      link: '?component=vacuum',
      visibility: ['person.adrien'],
    },
    {
      standalone: false,
      entity_kind: 'climate',
      entities_to_exclude: ['climate.clou'],
      active_icon: 'sci:radiator-heat',
      inactive_icon: 'sci:radiator-waiting',
      name: 'Radiators',
      state_on: ['auto', 'heat'],
      state_error: null,
      link: '?component=climate',
      visibility: ['person.adrien'],
    },
    {
      standalone: false,
      entity_kind: 'switch',
      entities_to_exclude: [
        'switch.la_boite_a_cha_alarm_1_2',
        'switch.la_boite_a_nard_alarm_1_2',
        'switch.la_boite_a_nard_alarm_2_2',
        'switch.la_boite_a_nard_alarm_3_2',
        'switch.la_boite_a_nard_alarm_4_2',
        'switch.zigbee2mqtt_bridge_permit_join',
        'switch.zbmini_l_charlotte',
        'switch.zbmini_l_dressing_parent',
        'switch.zbmini_l_toilette_etage',
        'switch.zbmini_l_leonard',
        'switch.zbmini_l_cuisine',
        'switch.zbmini_l_parent',
        'switch.zbmini_l_terrasse',
        'switch.zbmini_l_bureau',
        'switch.zbmini_l_dressing_bureau',
        'switch.zbmini_l_salle_de_bain_lavabo',
        'switch.zbmini_l_salle_de_bain_baignoire',
        'switch.zbmini_l_mezzanine',
        'switch.zbmini_l_escalier',
        'switch.zbmini_l_couloir_haut',
        'switch.nodon_chauffe_eau',
        'switch.nodon_prises_tv',
        'switch.zbmini_l_douche_parent',
        'switch.zbmini_l_lavabo_parent',
        'switch.nodon_vmc_parent',
        'switch.zbmini_l_couloir_entree',
        'switch.zbmini_l_lampe_salon',
        'switch.zbmini_l_couloir_bas',
        'switch.nous_salon',
        'switch.zbmini_l_salon',
        'switch.nous_salle_a_manger',
        'switch.nodon_vmc_etage',
        'switch.zbmini_l_bibliotheque',
        'switch.zbmini_l_sam',
      ],
      active_icon: 'mdi:power-plug-outline',
      inactive_icon: 'mdi:power-plug-off-outline',
      name: 'Plug',
      state_on: ['on'],
      state_error: null,
      link: '?component=plugs',
      visibility: ['person.adrien'],
    },
  ],
};
