export const config = {
  header: {
    message: 'Welcome',
  },
  weather: {
    activate: true,
    sun_entity: 'sun.sun',
    weather_entity: 'weather.a_long-long_city_name',
  },
  tiles: [
    {
      standalone: false,
      entity_kind: 'light',
      entity_to_exclude: [],
      active_icon: 'mdi:lightbulb-on-outline',
      inactive_icon: 'mdi:lightbulb-outline',
      name: 'Ligths',
      state_on: ['on'],
      state_error: null,
      link: '#',
    },
    {
      standalone: false,
      entity_kind: 'climate',
      entity_to_exclude: ['climate.stove'],
      active_icon: 'mdi:radiator',
      inactive_icon: 'mdi:radiator-disabled',
      name: 'Radiators',
      state_on: ['on', 'auto'],
      state_error: null,
      link: '#',
    },
    {
      standalone: true,
      entity: 'climate.stove',
      active_icon: 'sci:stove-heat',
      inactive_icon: 'sci:stove-off',
      name: 'Stove',
      state_on: ['heat', 'cool'],
      state_error: null,
      link: '#',
    },
    {
      standalone: true,
      entity: 'vacuum.cleaner',
      active_icon: 'mdi:robot-vacuum',
      inactive_icon: 'sci:vacuum-sleep',
      name: 'Vacuum',
      state_on: ['cleaning', 'returning'],
      state_error: 'error',
      link: '#',
    },
  ],
};
